FROM python:3.12.1-bullseye

# Définit le fuseau horaire (remplacez par votre fuseau horaire souhaité)
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Définit le répertoire de travail dans le conteneur
WORKDIR /API/

# Copie les fichiers de dépendances Python dans le conteneur
COPY ./API/ /API/
COPY ./requirements.txt /API/

# Installe les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Installer redis et suppirmer le cache
RUN apt-get update && apt-get install -y redis-server pushpin && apt-get clean

RUN rm -rf /var/lib/apt/lists/*

COPY ./pushpin.conf /etc/pushpin/pushpin.conf

# Execute pour debug si nécessaire
# CMD [ "tail", "-f", "/dev/null" ]

# Utiliser supervisord pour démarrer les services
CMD redis-server --daemonize yes \
    && pushpin \
    && python manage.py wait_for_db \
    && python manage.py makemigrations \
    && python manage.py migrate \
    && tail -f /dev/null