version: '3'

services:
  django-backend:
    platform: linux/amd64
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../backend/API:/API #Volume for DEV
    networks:
      private-network:
        ipv4_address: 172.69.69.2
    
  timescaledb:
    platform: linux/amd64
    image: timescale/timescaledb:latest-pg12
    env_file:
      - .env
    container_name: timescaledb
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./my_postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      private-network:
        ipv4_address: 172.69.69.3

  vuejs-frontend :
    platform: linux/amd64
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: vuejs-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      private-network:
        ipv4_address: 172.69.69.4

  # A utiliser pour la gestion de la base de donnée avec UI : localhost:8080
  adminer:
    platform: linux/amd64
    image: adminer
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      private-network :
        ipv4_address: 172.69.69.5

networks:
  private-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.69.69.0/24