version: '3'

services:
  django-backend:
    platform: linux/amd64
    image: piorigin/django-sae-devapp-alt:latest
    build:
      context: ../backend
      dockerfile: Dockerfile.Prod
    depends_on:
      - timescaledb
    env_file:
      - .env
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
        - ../backend/API/project/api.log:/API/project/api.log
    #   - ../backend/API:/API #Volume for DEV when needed to prepare the production
    networks:
      private-network:
        ipv4_address: 172.69.69.2
    
  timescaledb:
    platform: linux/amd64
    image: timescale/timescaledb:latest-pg12
    env_file:
      - .env
    container_name: timescaledb
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      private-network:
        ipv4_address: 172.69.69.3

  vuejs-frontend :
    platform: linux/amd64
    image: piorigin/vuejs-sae-devapp-alt:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: vuejs-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      private-network:
        ipv4_address: 172.69.69.4

networks:
  private-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.69.69.0/24