name: Docker Compose CI

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build-and-push:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@latest_version
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Django Backend Docker image
      uses: docker/build-push-action@latest_version
      with:
        context: ./backend
        file: ./backend/Dockerfile.Prod
        push: true
        tags: piorigin/django-sae-devapp-alt:latest

    - name: Build and push VueJS Frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: piorigin/vuejs-sae-devapp-alt:latest
